= Deploy Microservices
include::_attributes.adoc[]

ifdef::workshop[]
Create an environment variable for your user and log into OpenShift.

[source,bash,subs="+macros,+attributes"]
----
export WORKSHOP_USER=<your-username-number>


#Example:
export WORKSHOP_USER=1

oc login -u user$WORKSHOP_USER -p openshift {ocpurl}
----
endif::workshop[]

[#deploycustomer]
== Deploy customer

Make sure you have setup the project/namespace

[source,bash,subs="+macros,+attributes"]
----
kubectl create namespace tutorial{namespace-suffix}
kubectl config set-context $(kubectl config current-context) --namespace=tutorial{namespace-suffix}
----

Then clone the git repository

[source,bash,subs="+macros,+attributes"]
----
git clone https://github.com/rafabene/istio-tutorial
cd istio-tutorial
----

Start deploying the microservice projects, starting with customer

Make sure `istioctl` is in your `PATH`:

[source,bash,subs="+macros,+attributes"]
----
$ istioctl version
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
----

=== Deploy Customer 

NOTE: You will deploy docker images that were privously built. If you want to build customer visit: xref:2build-microservices.adoc#buildcustomer[Build Customer]

Now let's deploy the customer pod with its sidecar

[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f <(istioctl kube-inject -f link:{github-repo}/{customer-repo}/kubernetes/Deployment.yml[{customer-repo}/kubernetes/Deployment.yml]) -n tutorial{namespace-suffix}
kubectl create -f link:{github-repo}/{customer-repo}/kubernetes/Service.yml[{customer-repo}/kubernetes/Service.yml] -n tutorial{namespace-suffix}
----

=== Expose customer

Since the `customer` service is the one our users will interact with, let's add an OpenShift Route that exposes that endpoint.

ifndef::workshop[]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -f link:{github-repo}/{customer-repo}/kubernetes/Gateway.yml[{customer-repo}/kubernetes/Gateway.yml] -n tutorial{namespace-suffix}

kubectl get pods -w -n tutorial{namespace-suffix}
----
endif::workshop[]

ifdef::workshop[]
[source,bash,subs="+macros,+attributes"]
----
envsubst < link:{github-repo}/{customer-repo}/kubernetes/Gateway.workshop.yml[{customer-repo}/kubernetes/Gateway.workshop.yml] | kubectl create -f - -n tutorial{namespace-suffix}

kubectl get pods -w -n tutorial{namespace-suffix}
----
endif::workshop[]

IMPORTANT: If your pod fails with `ImagePullBackOff`, it's possible that your current terminal isn't using the proper Docker Environment. See link:#setup-environment[Setup environment].

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[#deploypreference]
== Deploy Preference

NOTE: You will deploy docker images that were privously built. If you want to build preference visit: xref:2build-microservices.adoc#buildpreference[Build Preference]

Now let's deploy the preference pod with its sidecar

[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f <(istioctl kube-inject -f link:{github-repo}/{preference-repo}/kubernetes/Deployment.yml[{preference-repo}/kubernetes/Deployment.yml])  -n tutorial{namespace-suffix}
kubectl create -f link:{github-repo}/{preference-repo}/kubernetes/Service.yml[{preference-repo}/kubernetes/Service.yml] -n tutorial{namespace-suffix}
----

=== Wait preference to be deployed

[source, bash,subs="+macros,+attributes"]
----
kubectl get pods -w -n tutorial{namespace-suffix}
----

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

[#deployrecommendation]
== Deploy Recommendation

NOTE: You will deploy docker images that were privously built. If you want to build recommendation visit: xref:2build-microservices.adoc#buildrecommendation[Build Recommendation]

Now let's deploy the recommendation pod with its sidecar

[source,bash,subs="+macros,+attributes"]
----
kubectl apply -f <(istioctl kube-inject -f link:{github-repo}/{recommendation-repo}/kubernetes/Deployment.yml[{recommendation-repo}/kubernetes/Deployment.yml]) -n tutorial{namespace-suffix}
kubectl create -f link:{github-repo}/{recommendation-repo}/kubernetes/Service.yml[{recommendation-repo}/kubernetes/Service.yml] -n tutorial{namespace-suffix}
kubectl get pods -w -n tutorial{namespace-suffix}
----

=== Wait recommendation to be deployed

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press `Ctrl+C`

Test the customer endpoint

[source,bash,subs="+macros,+attributes"]
----
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')

curl $(minikube ip):$INGRESS_PORT/{path}
----

it should now return

[source,bash,subs="+macros,+attributes"]
----
customer => preference => recommendation v1 from '99634814-sf4cl': 1
----


[#redeployingcode]
== Updating Redeploying Code

When you wish to change code (e.g. editing the .java files) and wish to "redeploy", simply:

[source,bash]
----
cd {servicename}/java/{quarkus|springboot|vertx}

vi src/main/java/com/redhat/developer/demos/{servicename}/{Servicename}{Controller|Verticle}.java
----

Make your changes, save it and then:

[source,bash]
----
mvn clean package
eval $(minikube docker-env)
docker build -t example/{servicename}:v1 .

kubectl get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename}
kubectl get pods -o jsonpath='{.items[*].metadata.name}' -l app={servicename},version=v1
kubectl delete pod -l app={servicename},version=v1 -n tutorial{namespace-suffix}
----

Why the delete pod?

Based on the Deployment configuration, Kubernetes/OpenShift will recreate the pod, based on the new docker image as it attempts to keep the desired replicas available

[source,bash]
----
kubectl describe deployment {servicename} -n tutorial{namespace-suffix} | grep Replicas
----
